# Generated by Django 3.0.5 on 2020-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200427_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconversation',
            name='is_listening',
            field=models.BooleanField(default=False),
        ),
    ]
