# Generated by Django 3.0.5 on 2020-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_friendrequest_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconversation',
            name='is_listening',
            field=models.BooleanField(default=True),
        ),
    ]
